[mgr]
  prepend_keymap = [
    { on = "<F3>", run = "plugin mediainfo -- toggle-metadata", desc = "Toggle media preview metadata" },
    { on = "<F4>", run = "plugin mediainfo -- toggle-preview", desc = "Toggle media preview image" },

    # Hide and show metadata, image
    { on = "<F6>", run = "plugin mediainfo -- hide-metadata", desc = "Hide media preview metadata" },
    { on = "<F7>", run = "plugin mediainfo -- hide-preview", desc = "Hide media preview image" },

    { on = "<F8>", run = "plugin mediainfo -- show-metadata", desc = "Show media preview metadata" },
    { on = "<F9>", run = "plugin mediainfo -- show-preview", desc = "Show media preview image" },

    # Reset to defautl settings in yazi.toml file
    { on = "<F5>", run = "plugin mediainfo -- reset", desc = "Reset media preview to default settings" },

    # Use multiple actions
    { on = "<F10>", run = "plugin mediainfo -- --toggle-preview --toggle-metadata", desc = "Toggle both media preview image and metadata" },
    { on = "<F11>", run = "plugin mediainfo -- --show-preview --hide-metadata", desc = "Show media preview image and hide metadata" },
    # You can also use all of them together (7 actions above). Priority is reset > toggle > hide > show
    { on = "<F12>", run = "plugin mediainfo -- --show-preview --hide-metadata --reset --show-metadata --hide-preview", desc = "Show media preview image and hide metadata" },

    # Smar-enter plugin
    { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
    # vcs-files plugin
    { on = [ "g", "c" ], run = "plugin vcs-files", desc = "Show Git file changes" },
    # zoom plugin
    { on = [ "+" ], run = "plugin zoom 1", desc = "Zoom in hovered file" },
    { on = [ "-" ], run = "plugin zoom -1", desc = "Zoom out hovered file" },
    # smart-filter plugin
    { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
    # chmod plugin
    { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files" },
    # diff plugin
    { on = "<C-d>", run = "plugin diff", desc = "Diff the selected with the hovered file" },
    # lazygit plugin
    { on = [ "g", "l" ], run = "plugin lazygit", desc = "Open lazygit" },
    # pandoc plugin
    { on = ["c", "p"], run = "plugin pandoc", desc = "Pandoc: Interative Convert" },
    # copy file contents plugin
    { on = "A-y", run = ["plugin copy-file-contents"], desc = "Copy file contents" },
    # command palette plugin
    { on = "<C-p>", run = "plugin command", desc = "Open command palette" },
  ]
