# vim:ft=kitty

## name: Tokyo Night Flash Goddess Storm
## author: Custom - Flash Goddess Storm palette

background              #24283b
foreground              #DED09F
selection_background    #4B233E
selection_foreground    #DED09F
url_color               #9D7CD8
cursor                  #DED09F
cursor_text_color       #24283b

# Tabs
active_tab_background   #9D7CD8
active_tab_foreground   #24283b
inactive_tab_background #202825
inactive_tab_foreground #A88E71
tab_bar_background      #202825

# Windows
active_border_color     #9D7CD8
inactive_border_color   #4B233E

# normal (color0-7)
color0  #202825   # black
color1  #822F36   # red
color2  #8D8442   # green
color3  #D56920   # yellow/orange
color4  #9D7CD8   # blue → bright purple
color5  #9D7CD8   # magenta → bright purple
color6  #A88E71   # cyan → beige
color7  #C0CDCC   # white → light brown

# bright (color8-15)
color8  #4B233E   # bright black → dark purple
color9  #822F36   # bright red
color10 #8D8442   # bright green
color11 #D56920   # bright yellow
color12 #9D7CD8   # bright blue
color13 #9D7CD8   # bright magenta
color14 #A88E71   # bright cyan
color15 #DED09F   # bright white → cream

# extended
color16 #D56920   # orange
color17 #822F36   # dark red
